components:
    schemas:
        book:
            description: '[book](#/schemas/book)'
            properties:
                id:
                    type: string
                title:
                    type: string
            required:
                - id
                - title
            type: object
        books_response:
            description: '[books_response](#/schemas/books_response)'
            properties:
                books:
                    items:
                        $ref: '#/components/schemas/book'
                    type: array
                total:
                    type: integer
            required:
                - total
                - books
            type: object
        error:
            description: '[error](#/schemas/error)'
            properties:
                message:
                    type: string
            required:
                - message
            type: object
        error_response:
            description: '[error_response](#/schemas/error_response)'
            properties:
                error:
                    $ref: '#/components/schemas/error'
            required:
                - error
            type: object
info:
    description: Pixality API
    title: Pixality API
    version: "1.0"
openapi: 3.0.0
paths:
    /api/1.0/books:
        get:
            operationId: BooksGet
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/books_response'
                    description: books_response
                "400":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error_response'
                    description: error_response
                "401":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error_response'
                    description: error_response
                "403":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error_response'
                    description: error_response
                "404":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error_response'
                    description: error_response
                "500":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error_response'
                    description: error_response
                "503":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/error_response'
                    description: error_response
            summary: Get books
            tags:
                - books
servers:
    - description: Current Host
      url: ""
tags:
    - name: books
